### ISSUE TITLE
支持 TCP吗 有计划支持不

### ISSUE THREAD

**Issue by sgf** [xljiulang/NetworkSocket#8]
支持 TCP吗 有计划支持不

**Comment by xljiulang** [comment]
tcp是传输协议，networksocket的所支持的所有上层协议都是基于tcp

**Comment by sgf** [comment]
@xljiulang 我知道 但是 我的意思是 不基于任何TCP之上的高层协议。而是仅仅使用 TCP。

**Comment by xljiulang** [comment]
那写自定义middleware就可以
